version: 2
updates:
  - package-ecosystem: "pip"
    directory: "src"
    schedule:
      interval: "daily"
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
